"""Initial migration.

Revision ID: f57aaefaabff
Revises: 
Create Date: 2022-04-26 16:38:01.141275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f57aaefaabff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('proverbs', 'chinese',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('proverbs', 'pinyin',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('proverbs', 'p_translation',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_unique_constraint(None, 'proverbs', ['chinese'])
    op.create_unique_constraint(None, 'proverbs', ['pinyin'])
    op.create_unique_constraint(None, 'proverbs', ['p_translation'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'proverbs', type_='unique')
    op.drop_constraint(None, 'proverbs', type_='unique')
    op.drop_constraint(None, 'proverbs', type_='unique')
    op.alter_column('proverbs', 'p_translation',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('proverbs', 'pinyin',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('proverbs', 'chinese',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
