name: AWS EC2 Continuous Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: "Deploy to AWS EC2 Instance"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Deploy in EC2
      env:
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        HOSTNAME : ${{ secrets.SSH_IP }}
        USER_NAME : ${{ secrets.SSH_USER }}          
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -i private_key -o UserKnownHostsFile=${{ secrets.SSH_KNOWN_HOSTS }} StrictHostKeyChecking=no -tt ${USER_NAME}@${HOSTNAME} '
        
        cd ${{ secrets.PROJECT_ROOT }} && 
        sudo git fetch && 
        sudo git reset --hard origin/main && 
        docker-compose down && 
        docker-compose up -d --build '